#!/bin/bash

CLASSES=/s/bach/k/under/jordantp/workspace/cs455/CS455-HW2-PC/
SCRIPT="cd $CLASSES;
java -cp . cs455.scaling.client.Client '$2' '$3' '$4'"
#$1 is the command-line argument
for((j=1;j<=$1;j++));
do
    COMMAND='gnome-terminal'
    for i in `cat machine_list`
    do
        echo 'logging into '$i
        OPTION='--tab -e "ssh -t '$i' '$SCRIPT'"'
        COMMAND+=" $OPTION"
    done
    eval $COMMAND &
done
